### ISSUE TITLE
how do I build

### ISSUE THREAD

**Issue by an-OK-squirrel** [liam4/slw#4]
i am sorry I AM NOT A COMPUTER PERSON!!!!

**Comment by an-OK-squirrel** [comment]
running `gulp` leads to 

```
[15:21:27] Using gulpfile E:\github\slw\gulpfile.js
C:\Users\meme\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at C:\Users\meme\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by towerofnix** [comment]
``` bash
$ git clone ..
$ npm install
$ gulp watch
# 🎉
```

My fault for not including a readme. :shipit:

**Comment by an-OK-squirrel** [comment]
thank

**Comment by an-OK-squirrel** [comment]
should I install gulp globally or something ??

**Comment by an-OK-squirrel** [comment]
hmm, still not working for me.

**Comment by towerofnix** [comment]
Same issue?

**Comment by towerofnix** [comment]
Oh yeah probably install it globally. That's what I'm doing :P

**Comment by an-OK-squirrel** [comment]
Works after I did a few other things like install gulp cli :tada: thanks, mr liam

**Comment by an-OK-squirrel** [comment]
hrmmm, it never finishes building though. it says it finished but doesnt exit the program

**Comment by an-OK-squirrel** [comment]
http://i.imgur.com/tIH0vmF.png

**Comment by towerofnix** [comment]
blame alex for turning like 5kb of code into 101kb.

also that's good right? that's what it should do after building - try opening index.html

**Comment by bates64** [comment]
``` sh
$ yarn global add gulp-cli # npm install -g gulp-cli
$ gulp watch
$ gulp build
```
